import {
  PTAidoKlinika,
  PTDigitalBusinessCard,
  PTGoa,
  PTGoaPwa,
  PTGoaWeb,
  PTGposone,
  PTMediatechYummyInventory,
  PTMediatechYummyStocktake,
  PTMediatechYummyStockwaste,
  PTMuatmuat,
  PTNewusSisarpas,
  PTSportirenaMobile,
  PTSportirenaOwner,
} from "../../../../public/images";

export const projects = [
  {
    thumbnail: PTGoa,
    year: 2025,
    project: "Goapotik Landing Page",
    madeAt: "PT Karsa Inti Tuju Askara",
    role: "FE",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Axios",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
    link: "https://www.goapotik.com",
  },
  {
    thumbnail: PTGposone,
    year: 2024,
    project: "GPOS One",
    madeAt: "PT Karsa Inti Tuju Askara",
    role: "FE",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Axios",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Mantine",
      "Tanstack Query",
    ],
    link: "https://account.gpos.id",
  },
  {
    thumbnail: PTGoaPwa,
    year: 2024,
    project: "Goapotik PWA",
    madeAt: "PT Karsa Inti Tuju Askara",
    role: "FE",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Axios",
      "ESLint",
      "React Hook Form",
      "Tanstack Query",
    ],
    link: "https://stgpwa.goapotik.com",
  },
  {
    thumbnail: PTNewusSisarpas,
    year: 2025,
    project: "Sisarpas Dinas Pendidikan Lampung",
    madeAt: "Newus Technology",
    role: "BE",
    builtWith: [
      "Typescript",
      "Node.js",
      "ExpressJS",
      "PostgreSQL",
      "Prisma",
      "ESLint",
    ],
    link: "https://sisarpas.newus.id/",
  },
  {
    thumbnail: PTSportirenaOwner,
    year: 2024,
    project: "Sportirena Owner",
    madeAt: "PT Technova Optima Prima",
    role: "FE",
    builtWith: [
      "Typescript",
      "React.js",
      "TailwindCSS",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
    link: "https://sportirena.com:3137/",
  },
  {
    thumbnail: PTGoaWeb,
    year: 2023,
    project: "Goapotik Web Store",
    madeAt: "PT Karsa Inti Tuju Askara",
    role: "FE",
    builtWith: ["AdonisJS", "VueJS", "Bootstrap", "Git"],
    link: "https://sisarpas.newus.id/",
  },
  {
    thumbnail: PTAidoKlinika,
    year: 2022,
    project: "Aido Klinika",
    madeAt: "Aido Health Indonesia",
    role: "FS",
    builtWith: ["Node.js", "ExpressJS", "MySQL", "React.js", "Bootstrap"],
  },
  {
    thumbnail: PTMediatechYummyInventory,
    year: 2022,
    project: "Yummy Corps - Product Inventory",
    madeAt: "PT Mediatechindo",
    role: "FE",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Axios",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
  },
  {
    thumbnail: PTMediatechYummyStocktake,
    year: 2022,
    project: "Yummy Corps - Product Stocktake",
    madeAt: "PT Mediatechindo",
    role: "FE",
    builtWith: ["React.js", "TailwindCSS", "TypeScript", "Tanstack Query"],
  },
  {
    thumbnail: PTMediatechYummyStockwaste,
    year: 2022,
    project: "Yummy Corps - Product Stockwaste",
    madeAt: "PT Mediatechindo",
    role: "FE",
    builtWith: ["React.js", "TailwindCSS", "TypeScript", "Tanstack Query"],
  },
  {
    year: 2025,
    project: "Chat Service",
    madeAt: "Weslic",
    role: "BE",
    builtWith: [
      "Typescript",
      "AdonisJS",
      "PostgreSQL",
      "ESLint",
      "Prisma",
      "Socket.io",
      "OneSignal",
      "FCM",
    ],
  },
  {
    thumbnail: PTMuatmuat,
    year: 2025,
    project: "Muatmuat Merchant",
    madeAt: "PT AZlogistik",
    role: "FE",
    builtWith: ["Next.js", "TailwindCSS", "Axios"],
    link: "https://muatmuat.com/",
  },
  {
    thumbnail: PTSportirenaMobile,
    year: 2023,
    project: "Sportirena Mobile",
    madeAt: "PT Technova Optima Prima",
    role: "FE",
    builtWith: [
      "React Native",
      "ESlint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
  },
  {
    year: 2022,
    project: "Aido Appointment System",
    madeAt: "Aido Health Indonesia",
    role: "FS",
    builtWith: [
      "React.js",
      "Bootstrap",
      "MySQL",
      "Node.js",
      "ExpressJS",
      "Sequelize",
    ],
  },
  {
    year: 2025,
    project: "Goapotik Loaylty Dashboard",
    madeAt: "PT Karsa Inti Tuju Askara",
    role: "FS",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Prisma",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
  },
  {
    thumbnail: PTDigitalBusinessCard,
    year: 2024,
    project: "Digital Business Card",
    madeAt: "PT Technova Optima Prima",
    role: "FE",
    builtWith: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "ESLint",
      "Prettier",
      "React Hook Form",
      "Tanstack Query",
    ],
  },
];
